# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    environment: production

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: export DB_NAME=${{secrets.DB_NAME}} && export HOST=${{secrets.HOST}}
    - run: export JWT_SKEY=${{secrets.JWT_SKEY}} && export PASS=${{secrets.PASS}}
    - run: export USER=${{secrets.USER}} && export NODE_ENV='production'
    - run: npm ci
    - run: cd ./client && npm ci && npm run build && cd ..
    - run: pm2 restart 0 --update-env
